// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(AccountSystem))]
    [Migration("20210809210850_initial41")]
    partial class initial41
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BankAccountNumber")
                        .HasColumnType("int");

                    b.Property<int>("BankNumber")
                        .HasColumnType("int");

                    b.Property<int?>("InvestmentPolicyTypesId")
                        .HasColumnType("int");

                    b.Property<int>("ManagementFee")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvestmentPolicyTypesId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("DAL.InvestmentPolicyTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InvestmentPolicyTypes");
                });

            modelBuilder.Entity("DAL.Personal", b =>
                {
                    b.Property<string>("Tz")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Tz");

                    b.ToTable("Personals");
                });

            modelBuilder.Entity("DAL.PersonalInAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonalTypesId")
                        .HasColumnType("int");

                    b.Property<string>("PersonalTz")
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PersonalTypesId");

                    b.HasIndex("PersonalTz");

                    b.ToTable("PersonalInAccounts");
                });

            modelBuilder.Entity("DAL.PersonalTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonalTypes");
                });

            modelBuilder.Entity("DAL.Account", b =>
                {
                    b.HasOne("DAL.InvestmentPolicyTypes", "InvestmentPolicyTypes")
                        .WithMany()
                        .HasForeignKey("InvestmentPolicyTypesId");

                    b.Navigation("InvestmentPolicyTypes");
                });

            modelBuilder.Entity("DAL.PersonalInAccount", b =>
                {
                    b.HasOne("DAL.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("DAL.PersonalTypes", "PersonalTypes")
                        .WithMany()
                        .HasForeignKey("PersonalTypesId");

                    b.HasOne("DAL.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalTz");

                    b.Navigation("Account");

                    b.Navigation("Personal");

                    b.Navigation("PersonalTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
